Repository cs2113-ay1819s2-t08-1/main, pull requests merged in 2019-04, with the labels that each got.

#59 sort command working
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
Labels: priority.Medium

#65 v1.3 fix after merge
  src/main/java/seedu/address/logic/commands/EditBeneficiaryCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/project/Project.java
  src/main/java/seedu/address/model/volunteer/Volunteer.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/VolunteerCard.java
  src/main/resources/view/VolunteerListCard.fxml
Labels: priority.High, type.Bug

#72 fix bug for assign command and add project command
  src/main/java/seedu/address/logic/commands/AssignBeneficiaryCommand.java
  src/main/java/seedu/address/model/beneficiary/Beneficiary.java
  src/main/java/seedu/address/model/project/ProjectTitle.java
  src/main/java/seedu/address/storage/JsonAdaptedProject.java
Labels: priority.High, type.Bug

#84 Sort command fixed + checkstyle fixed
  src/main/java/seedu/address/logic/commands/MapCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/MapCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/volunteer/UniqueVolunteerList.java
Labels: priority.High

#112 Update for v 1.4
  build.gradle
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/AddBeneficiaryCommand.java
  src/main/java/seedu/address/logic/commands/AssignBeneficiaryCommand.java
  src/main/java/seedu/address/logic/commands/AssignVolunteerCommand.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/DeleteBeneficiaryCommand.java
  src/main/java/seedu/address/logic/commands/DeleteProjectCommand.java
  src/main/java/seedu/address/logic/commands/EditBeneficiaryCommand.java
  src/main/java/seedu/address/logic/commands/FindBeneficiaryCommand.java
  src/main/java/seedu/address/logic/commands/ListBeneficiaryCommand.java
  src/main/java/seedu/address/logic/commands/SummaryBeneficiaryCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntaxBeneficiary.java
  src/main/java/seedu/address/logic/parser/DeleteBeneficiaryCommandParser.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/beneficiary/Beneficiary.java
  src/main/java/seedu/address/model/project/Project.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: priority.Medium, type.Bug, type.Enhancement

#126 fix undo bugs and do some refactoring
  src/main/java/seedu/address/logic/commands/AssignVolunteerCommand.java
  src/main/java/seedu/address/logic/commands/DeleteProjectCommand.java
  src/main/java/seedu/address/logic/commands/SummaryBeneficiaryCommand.java
  src/main/java/seedu/address/logic/commands/beneficiary/AddBeneficiaryCommand.java
  src/main/java/seedu/address/logic/commands/beneficiary/DeleteBeneficiaryCommand.java
  src/main/java/seedu/address/logic/commands/beneficiary/EditBeneficiaryCommand.java
  src/main/java/seedu/address/logic/commands/beneficiary/FindBeneficiaryCommand.java
  src/main/java/seedu/address/logic/commands/beneficiary/ListBeneficiaryCommand.java
  src/main/java/seedu/address/logic/commands/beneficiary/SummaryBeneficiaryCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntaxBeneficiary.java
  src/main/java/seedu/address/logic/parser/ParserUtilBeneficiary.java
  src/main/java/seedu/address/logic/parser/beneficiary/AddBeneficiaryCommandParser.java
  src/main/java/seedu/address/logic/parser/beneficiary/DeleteBeneficiaryCommandParser.java
  src/main/java/seedu/address/logic/parser/beneficiary/EditBeneficiaryCommandParser.java
  src/main/java/seedu/address/logic/parser/beneficiary/FindBeneficiaryCommandParser.java
  src/main/java/seedu/address/model/beneficiary/Beneficiary.java
  src/main/java/seedu/address/ui/BeneficiaryStatsWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/beneficiary/BeneficiaryCard.java
  src/main/java/seedu/address/ui/beneficiary/BeneficiaryListPanel.java
Labels: priority.High, type.Bug

#127 Adding test cases for beneficiary management
  src/main/java/seedu/address/logic/commands/beneficiary/AddBeneficiaryCommand.java
  src/main/java/seedu/address/logic/commands/beneficiary/DeleteBeneficiaryCommand.java
  src/main/java/seedu/address/logic/commands/beneficiary/EditBeneficiaryCommand.java
  src/main/java/seedu/address/logic/commands/beneficiary/FindBeneficiaryCommand.java
  src/main/java/seedu/address/logic/commands/beneficiary/ListBeneficiaryCommand.java
  src/main/java/seedu/address/logic/commands/beneficiary/SummaryBeneficiaryCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/beneficiary/AddBeneficiaryCommandTest.java
  src/test/java/seedu/address/logic/commands/beneficiary/BeneficiaryCommandTestUtil.java
  src/test/java/seedu/address/logic/commands/beneficiary/DeleteBeneficiaryCommandTest.java
  src/test/java/seedu/address/logic/commands/beneficiary/EditBeneficiaryCommandTest.java
  src/test/java/seedu/address/logic/commands/beneficiary/EditBeneficiaryDescriptorTest.java
  src/test/java/seedu/address/logic/commands/beneficiary/ListBeneficiaryCommandTest.java
  src/test/java/seedu/address/logic/parser/beneficiary/AddBeneficiaryCommandParserTest.java
  src/test/java/seedu/address/logic/parser/beneficiary/DeleteBeneficiaryCommandParserTest.java
  src/test/java/seedu/address/logic/parser/beneficiary/EditBeneficiaryCommandParserTest.java
  src/test/java/seedu/address/logic/parser/beneficiary/FindBeneficiaryCommandParserTest.java
  src/test/java/seedu/address/testutil/AddressBookBuilder.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
  src/test/java/seedu/address/testutil/beneficiary/BeneficiariesSyncProjects.java
  src/test/java/seedu/address/testutil/beneficiary/BeneficiaryBuilder.java
  src/test/java/seedu/address/testutil/beneficiary/BeneficiaryUtil.java
  src/test/java/seedu/address/testutil/beneficiary/EditBeneficiaryDescriptorBuilder.java
  src/test/java/seedu/address/testutil/beneficiary/TypicalBeneficiaries.java
Labels: priority.Medium, type.Task

#135 map command test + checkstyle
  articstranger.png}
  docs/DeveloperGuide.adoc
  docs/diagrams/MapSequenceDiagram.pptx
  docs/images/MapSequenceDiagram.png
  docs/images/Volunteerclasswithpoints.jpg
  ndhuu.png}
  quinnzzzzz.png}
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/MapCommand.java
  src/main/java/seedu/address/model/MapObject.java
  src/test/java/seedu/address/logic/commands/MapCommandTest.java
  src/test/java/seedu/address/logic/commands/beneficiary/AddBeneficiaryCommandTest.java
  src/test/java/seedu/address/logic/parser/MapCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalVolunteers.java
  swalahlah.png}
Labels: priority.High, type.Task

#133 Tag Author on my code
  _reposense/config.json
  docs/team/Huu.adoc
  src/main/java/seedu/address/logic/commands/AssignBeneficiaryCommand.java
  src/main/java/seedu/address/logic/commands/beneficiary/AddBeneficiaryCommand.java
  src/main/java/seedu/address/logic/commands/beneficiary/DeleteBeneficiaryCommand.java
  src/main/java/seedu/address/logic/commands/beneficiary/EditBeneficiaryCommand.java
  src/main/java/seedu/address/logic/commands/beneficiary/FindBeneficiaryCommand.java
  src/main/java/seedu/address/logic/commands/beneficiary/ListBeneficiaryCommand.java
  src/main/java/seedu/address/logic/commands/beneficiary/SummaryBeneficiaryCommand.java
  src/main/java/seedu/address/logic/parser/beneficiary/AddBeneficiaryCommandParser.java
  src/main/java/seedu/address/logic/parser/beneficiary/DeleteBeneficiaryCommandParser.java
  src/main/java/seedu/address/logic/parser/beneficiary/EditBeneficiaryCommandParser.java
  src/main/java/seedu/address/logic/parser/beneficiary/FindBeneficiaryCommandParser.java
  src/main/java/seedu/address/model/beneficiary/Beneficiary.java
  src/main/java/seedu/address/storage/JsonAdaptedBeneficiary.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/beneficiary/BeneficiaryCard.java
  src/main/java/seedu/address/ui/beneficiary/BeneficiaryListPanel.java
  src/test/java/seedu/address/logic/commands/beneficiary/AddBeneficiaryCommandTest.java
  src/test/java/seedu/address/logic/commands/beneficiary/BeneficiaryCommandTestUtil.java
  src/test/java/seedu/address/logic/commands/beneficiary/DeleteBeneficiaryCommandTest.java
  src/test/java/seedu/address/logic/commands/beneficiary/EditBeneficiaryCommandTest.java
  src/test/java/seedu/address/logic/commands/beneficiary/EditBeneficiaryDescriptorTest.java
  src/test/java/seedu/address/logic/commands/beneficiary/ListBeneficiaryCommandTest.java
  src/test/java/seedu/address/logic/parser/beneficiary/AddBeneficiaryCommandParserTest.java
  src/test/java/seedu/address/logic/parser/beneficiary/DeleteBeneficiaryCommandParserTest.java
  src/test/java/seedu/address/logic/parser/beneficiary/EditBeneficiaryCommandParserTest.java
  src/test/java/seedu/address/logic/parser/beneficiary/FindBeneficiaryCommandParserTest.java
  src/test/java/seedu/address/model/beneficiary/AddressTest.java
  src/test/java/seedu/address/model/beneficiary/BeneficiaryTest.java
  src/test/java/seedu/address/model/beneficiary/EmailTest.java
  src/test/java/seedu/address/model/beneficiary/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/beneficiary/NameTest.java
  src/test/java/seedu/address/model/beneficiary/PhoneTest.java
  src/test/java/seedu/address/model/beneficiary/UniqueBeneficiaryListTest.java
  src/test/java/seedu/address/testutil/beneficiary/BeneficiariesSyncProjects.java
  src/test/java/seedu/address/testutil/beneficiary/BeneficiaryBuilder.java
  src/test/java/seedu/address/testutil/beneficiary/BeneficiaryUtil.java
  src/test/java/seedu/address/testutil/beneficiary/EditBeneficiaryDescriptorBuilder.java
  src/test/java/seedu/address/testutil/beneficiary/TypicalBeneficiaries.java
Labels: priority.Medium, type.Task

#136 DG updated with considerations for filtered export
  docs/DeveloperGuide.adoc
Labels: priority.High, type.Task

#137 Update documentation
  README.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/BeneficiarySequenceDiagram.pptx
  docs/diagrams/ModelComponentClassDiagram.pptx
  docs/images/AddBeneficiary.png
  docs/images/BeneficiaryClassDiagram.jpg
  docs/images/BeneficiaryHardDeletionSequenceDiagram.png
  docs/images/EditBeneficiary.png
  docs/images/FindBeneficiary.png
  docs/images/HardDelete.png
  docs/images/ModelClassDiagram.png
  docs/images/SoftDelete.png
  docs/images/SummaryBeneficiary.png
  docs/images/SummaryBeneficiaryCommandSequenceDiagram.png
  docs/images/UiClassDiagram.png
  docs/team/Huu.adoc
  src/main/java/seedu/address/logic/commands/beneficiary/AddBeneficiaryCommand.java
  src/main/java/seedu/address/logic/commands/beneficiary/DeleteBeneficiaryCommand.java
  src/main/java/seedu/address/logic/commands/beneficiary/EditBeneficiaryCommand.java
  src/main/java/seedu/address/logic/commands/beneficiary/FindBeneficiaryCommand.java
  src/main/java/seedu/address/logic/commands/beneficiary/ListBeneficiaryCommand.java
  src/main/java/seedu/address/logic/commands/beneficiary/SummaryBeneficiaryCommand.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/MainWindow.fxml
Labels: priority.Medium, type.Task

#142 make developer guide consistent
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/SummaryBeneficiaryCommandSequenceDiagram.png
  docs/team/Huu.adoc
  src/main/java/seedu/address/logic/commands/beneficiary/SummaryBeneficiaryCommand.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: priority.Medium, type.Task

#143 Added Images for UG+DG
  docs/DeveloperGuide.adoc
  docs/images/CompleteSequenceDiagram.png
  docs/images/ProjectClass.png
  docs/images/addProject.png
  docs/images/assignB.png
  docs/images/assignSequence.png
  docs/images/assignV.png
  docs/images/complete.png
  docs/images/deleteProject.png
  docs/team/ZhaoJunRu.adoc
Labels: severity.Medium

#144 update DG
  docs/DeveloperGuide.adoc
  docs/images/Ui.png
  docs/team/Huu.adoc
  src/main/resources/view/MainWindow.fxml
Labels: priority.Medium

#151 PPP pdf documents
  docs/team/Huu.pdf
  docs/team/Jeremy wong.adoc
  docs/team/Jeremy.pdf
  docs/team/ZhaoJunRu.adoc
  docs/team/ZhaoJunRu.pdf
  docs/team/Zhuhui.adoc
  docs/team/zhuhui.pdf
Labels: severity.Medium

#152 Update DG for image
  docs/DeveloperGuide.adoc
  docs/images/login_successful.JPG
  docs/images/password_prompt.JPG
Labels: priority.Medium

#155 Fix bugs on documents
  docs/DeveloperGuide.adoc
  docs/team/JunRu.adoc
  docs/team/JunRu.pdf
  docs/team/ZhaoJunRu.pdf
Labels: severity.Medium

#160 update ug
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: priority.Medium
