Repository cs2113-ay1819s2-t08-1/main, pull requests merged in 2019-03, with the labels that each got.

#23 basic beneficiary commands
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AddProjectCommand.java
  src/main/java/seedu/address/logic/commands/AddVolunteer.java
  src/main/java/seedu/address/logic/commands/DeleteBeneficiaryCommand.java
  src/main/java/seedu/address/logic/commands/EditBeneficiaryCommand.java
  src/main/java/seedu/address/logic/commands/FindBeneficiaryCommand.java
  src/main/java/seedu/address/logic/commands/ListBeneficiaryCommand.java
  src/main/java/seedu/address/logic/commands/MapCommand.java
  src/main/java/seedu/address/logic/parser/AddBeneficiaryCommandParser.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddProjectCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/CliSyntaxBeneficiary.java
  src/main/java/seedu/address/logic/parser/CliSyntaxProject.java
  src/main/java/seedu/address/logic/parser/EditBeneficiaryCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/FindBeneficiaryCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/ParserUtilBeneficiary.java
  src/main/java/seedu/address/logic/parser/ParserUtilPerson.java
  src/main/java/seedu/address/logic/parser/ParserUtilProject.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/beneficiary/Beneficiary.java
  src/main/java/seedu/address/model/beneficiary/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/beneficiary/UniqueBeneficiaryList.java
  src/main/java/seedu/address/model/person/Age.java
  src/main/java/seedu/address/model/person/DietaryPreference.java
  src/main/java/seedu/address/model/person/EmergencyContact.java
  src/main/java/seedu/address/model/person/Emergency_contact.java
  src/main/java/seedu/address/model/person/MedicalCondition.java
  src/main/java/seedu/address/model/person/Race.java
  src/main/java/seedu/address/model/person/UniqueVolunteerList.java
  src/main/java/seedu/address/model/person/Volunteer.java
  src/main/java/seedu/address/model/project/Beneficiary.java
  src/main/java/seedu/address/model/project/Date.java
  src/main/java/seedu/address/model/project/Project.java
  src/main/java/seedu/address/model/project/ProjectTitle.java
  src/main/java/seedu/address/storage/JsonAdaptedBeneficiary.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: priority.High

#24 Map command updated
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/MapCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/MapCommandParser.java
  src/main/java/seedu/address/model/MapObject.java
Labels: priority.Medium

#37 Update DG, command line recommendation
  docs/DeveloperGuide.adoc
  docs/images/CommandLineRecommendationSequenceDiagram.png
Labels: priority.Medium

#55 Fix Volunteer Storage
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/volunteer/UniqueVolunteerList.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/MainWindow.fxml
Labels: priority.High, type.Bug
